### ISSUE TITLE
Naming Conventions

### ISSUE THREAD

**Issue by EthanNichols** [C0dedSurvivor/GravityPuzzle#1]
NIT (Nit picking)
Take a look at standard naming conventions for Unity. Folders are generally CamalCase

GameScripts should be Scripts. Then you can organize your scripts inside that folder.
Skins should be Art/Textures/Sprites.
resources should be capitalized to Resources
_Scenes shouldn't have an underscore at the front and be Scenes

**Comment by Jacob-Brosler** [comment]
Done and dusted
