### ISSUE TITLE
Enum for TileTypes

### ISSUE THREAD

**Issue by EthanNichols** [C0dedSurvivor/GravityPuzzle#2]
Map.cs the 2d map array I suggest using enums instead of ints

enum tilesTypes {
Nothing,
Goal,
Wall,
...
}

Makes the code cleaner and more sense than "random" numbers all over the place

**Comment by EthanNichols** [comment]
After going through your code and realizing that you're not generating maps, and manually creating them, I understand why you used ints.
B..u..t... it would still make more sense in some parts of code, and since enums are basically a reversed list (find the value [string] and return the key [int]) you should still be able to keep your numbers in your map creation.

**Comment by Jacob-Brosler** [comment]
Done
